// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MeetingsRef { uuid: string, title: string, datetime: string, number_ops: number, }