// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface RecordingDevices { input_device_name: string, output_device_name: string, }