// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelTurbo } from "./ModelTurbo";
import type { Prompt } from "./Prompt";

export interface Setting { uuid: string, assemblyai_api_token: string, openai_api_token: string, affinity_api_token: string, affinity_crm_list_id: string | null, prompts: Array<Prompt> | null, default_model: ModelTurbo | null, }