name: 'publish'
on:
  push:
    branches:
      - release
jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        settings:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'windows-latest'
            args: ''
    runs-on: ${{ matrix.settings.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.settings.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      - name: install frontend dependencies
        run: npm install
      - name: Install and copy ffmpeg on macOS
        if: runner.os == 'macOS'
        run: |
          brew install ffmpeg
          cp $(which ffmpeg) src-tauri/bin/ffmpeg-aarch64-apple-darwin
          cp $(which ffmpeg) src-tauri/bin/ffmpeg-x86_64-apple-darwin
          chmod +x src-tauri/bin/ffmpeg-aarch64-apple-darwin
          chmod +x src-tauri/bin/ffmpeg-x86_64-apple-darwin
      - name: Install 7z tool on Windows
        if: runner.os == 'Windows'
        run: choco install 7zip --version 19.00
      - name: Download ffmpeg for x86_64-pc-windows-msvc
        if: runner.os == 'Windows'
        run: |
          curl -L https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-essentials.7z -o src-tauri/bin/ffmpeg-x86_64-pc-windows-msvc.7z
          7z e src-tauri/bin/ffmpeg-x86_64-pc-windows-msvc.7z -osrc-tauri/bin/
          mv src-tauri/bin/ffmpeg.exe src-tauri/bin/ffmpeg-x86_64-pc-windows-msvc.exe
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.settings.args }}